### ISSUE TITLE
可不可以给个文档

### ISSUE THREAD

**Issue by yjacks** [visualfc/atk#25]
私想要用atk写GUI,但是无奈没有文档,又无法理解您的代码实现,所以希望给一个文档,帮助我们理解。
感恩不尽

**Comment by visualfc** [comment]
atk 是基于 tcl/tk 的包装，可以看一下 tk 相关的文档。

**Comment by yjacks** [comment]
> atk 是基于 tcl/tk 的包装，可以看一下 tk 相关的文档。

毕竟不是golang的方法啊......我同时对着源码,Demo和tkinter文档一小时才能分析一个方法

**Comment by 52LY** [comment]
[atk基础.md](https://github.com/visualfc/atk/files/8052915/atk.md)
很久之前写的总结，希望对你有所帮助

**Comment by yjacks** [comment]
> [atk基础.md](https://github.com/visualfc/atk/files/8052915/atk.md) 很久之前写的总结，希望对你有所帮助

感谢
