### ISSUE TITLE
custom TCL and TK dll path?

### ISSUE THREAD

**Issue by timelessnesses** [visualfc/atk#32]
i have a problem where if I don't install my tcl86.dll and tk86.dll from ActiveState installer and instead copy those to folder where the binary is it just wouldn't load those dll that I give it and instead always tries to load it somewhere else.  
so of instead of loading same path as always. can you make it supports to find dll in program's folder or maybe give an option to load from the bytearray (so i can go:embed it)?

**Comment by 52LY** [comment]
https://github.com/visualfc/atk/issues/8
hope to help you.

**Comment by timelessnesses** [comment]
ah i will try that

**Comment by timelessnesses** [comment]
looks like it works.
