### ISSUE TITLE
Failed to load tcl86t.dll: The specified module could not be found.

### ISSUE THREAD

**Issue by diomager** [visualfc/atk#5]
Failed to load tcl86t.dll: The specified module could not be found.

using activetcl 8.6.3.1

**Comment by mardukbp** [comment]
In a standard installation that file is located at `C:\ActiveState\bin`. Unless you unchecked the box, this path should have been added to the system-wide `%PATH%` environment variable. You can verify that with `echo %PATH%`.

**Comment by onur2677** [comment]
if you installed ActiveState PATH correctly, move your project directory  to  ```C:\go``` (For Example : ```C:\go\YOUR_PROJECT```) and build your project
